# Generated by Django 3.2.8 on 2021-10-31 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dataset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('channel', models.CharField(max_length=150)),
                ('country', models.CharField(max_length=2)),
                ('os', models.CharField(max_length=150)),
                ('impressions', models.IntegerField()),
                ('clicks', models.IntegerField()),
                ('installs', models.IntegerField()),
                ('spend', models.DecimalField(decimal_places=2, max_digits=9)),
                ('revenue', models.DecimalField(decimal_places=2, max_digits=9)),
            ],
        ),
    ]
